import Container from 'typedi';
import { ClaimIssuer } from './claim-issuer';
import { ClaimTopicsRegistry } from './claim-topics-registry';
import { Compliance } from './compliance';
import { ComplianceModule } from './compliance-module';
import { EligibilityVerification } from './eligibility-verification';
import { IdentityRegistry } from './identity-registry';
import { OnchainIDIdentity } from './onchain-id-identity';
import { Token } from './token';
import { TransferCompliance } from './transfer-compliance';
import { HolderEligibilityVerification } from './holder-eligibility-verification';

export * from './token';
export * from './compliance';
export * from './compliance-module';
export * from './identity-registry';
export * from './claim-issuer';
export * from './claim-topics-registry';
export * from './onchain-id-identity';
export * from './claim-issuer';
export * from './transfer-compliance';
export * from './eligibility-verification';
export * from './holder-eligibility-verification';

export const ClaimIssuerContract = Container.get(ClaimIssuer);
export const ClaimTopicsRegistryContract = Container.get(ClaimTopicsRegistry);
export const ComplianceModuleContract = Container.get(ComplianceModule);
export const ComplianceContract = Container.get(Compliance);
export const getEligibilityVerification = Container.get(EligibilityVerification);
export const IdentityRegistryContract = Container.get(IdentityRegistry);
export const OnchainIDIdentityContract = Container.get(OnchainIDIdentity);
export const TokenContract = Container.get(Token);
export const getTransferCompliance = Container.get(TransferCompliance);
export const getHolderEligibilityVerification = Container.get(HolderEligibilityVerification);
